### ISSUE TITLE
Can't import templates into Visual Studio Community 2017

### ISSUE THREAD

**Issue by chris3081** [vmware/vsphere-automation-sdk-.net#11]
Hi Folks,

Any chance of going releasing an update that allows us to import the templates into visual studio 2017?

9/03/2018 10:54:58 AM - Microsoft VSIX Installer
9/03/2018 10:54:58 AM - -------------------------------------------
9/03/2018 10:54:58 AM - vsixinstaller.exe version:
9/03/2018 10:54:58 AM - 15.6.152+ge95e4dd1ce
9/03/2018 10:54:58 AM - -------------------------------------------
9/03/2018 10:54:58 AM - Command line parameters:
9/03/2018 10:54:58 AM - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Projects\3rdparty\vmware.sdk.net\Project Template\Vmware-SDK-Automation-Sample-Template.vsix
9/03/2018 10:54:58 AM - -------------------------------------------
9/03/2018 10:54:58 AM - Microsoft VSIX Installer
9/03/2018 10:54:58 AM - -------------------------------------------
9/03/2018 10:55:06 AM - Initializing Install...
9/03/2018 10:55:06 AM - Extension Details...
9/03/2018 10:55:06 AM - 	Identifier         : Vmware_SDK_Automation_Sample_Template._1
9/03/2018 10:55:06 AM - 	Name               : Vmware  SDK  Automation Sample Template
9/03/2018 10:55:06 AM - 	Author             : ______
9/03/2018 10:55:06 AM - 	Version            : 1.0
9/03/2018 10:55:06 AM - 	Description        : Vmware  SDK  Automation Sample Template
9/03/2018 10:55:06 AM - 	Locale             : en-US
9/03/2018 10:55:06 AM - 	MoreInfoURL        : 
9/03/2018 10:55:06 AM - 	InstalledByMSI     : False
9/03/2018 10:55:06 AM - 	SupportedFrameworkVersionRange : [4.5,)
9/03/2018 10:55:06 AM - 
9/03/2018 10:55:06 AM - 	SignatureState     : Unsigned
9/03/2018 10:55:06 AM - 	Supported Products : 
9/03/2018 10:55:06 AM - 		Microsoft.VisualStudio.Community
9/03/2018 10:55:06 AM - 			Version : [14.0]
9/03/2018 10:55:06 AM - 
9/03/2018 10:55:06 AM - 	References         : 
9/03/2018 10:55:06 AM - Signature Details...
9/03/2018 10:55:06 AM - 	Extension is not signed.
9/03/2018 10:55:06 AM - 
9/03/2018 10:55:06 AM - Searching for applicable products...
9/03/2018 10:55:06 AM - Found installed product - Global Location
9/03/2018 10:55:06 AM - Found installed product - ssms
9/03/2018 10:55:06 AM - Found installed product - Visual Studio Community 2017
9/03/2018 10:55:06 AM - Found installed product - Visual Studio Community 2017
9/03/2018 10:55:07 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by vinpai** [comment]
Yes. I'll try to get this updated to VS 2017 before the next release. Thanks for pointing out the issue.

**Comment by chris3081** [comment]
Thanks vinpai, I've tested the replacement zip file and this is loading as expected.
