### ISSUE TITLE
APIs for file upload/download folder creation etc.

### ISSUE THREAD

**Issue by PerMalmberg** [vmware/vsphere-automation-sdk-.net#15]
Just like #10 and #14, I'm looking for additional APIs (file management, process execution). Is there a release planned with such APIs anytime soon?

We're currently using vim25, but are experiencing error "The guest operations agent could not be contacted" which, if the Internet is to be believed, is fixed in later version of the API, but if we're to update we'd prefer to use this new API - if only it supported the functionality we need.

**Comment by vinpai** [comment]
Can you elaborate a bit more on what workflow you are trying to automate ? Then I can check if any of those APIs are planned for the upcoming releases.

**Comment by PerMalmberg** [comment]
@vinpai This is a simplified version workflow we're currently using:

1. Restore guest snapshot
2. Send files
3. Execute command
4. Get console output from command
5. Download files
6. Suspend guest

If it matters, we're doing this for Linux, Windows and macOS guests.

We're also using power on/off and would like to create new machines from templates.

**Comment by alanrenouf** [comment]
@PerMalmberg Thanks for the detailed workflow, this helps with prioritization which we receive from various sources, I can confirm the suspend API is implemented in vSphere 6.7 as can be seen here: https://vdc-repo.vmware.com/vmwb-repository/dcr-public/423e512d-dda1-496f-9de3-851c28ca0814/0e3f6e0d-8d05-4f0c-887b-3d75d981bae5/VMware-vSphere-Automation-SDK-REST-6.7.0/docs/apidocs/operations/com/vmware/vcenter/vm/guest/power.standby-operation.html

As for the other APIs we are working to provide these in a future release, if you need more information please reach out to me for a conversation under NDA where I can learn more about your usage and we can discuss which order we are working on these in more detail.

**Comment by PerMalmberg** [comment]
@alanrenouf There's no need for an NDA from our side, what I wrote above accurately reflects our needs. Besides, as there are others (#10 & #14) also interested in additional APIs a public discussion would benefit not just us, but the entire community.

Can give me a rough timeline for when these APIs might be available? In short, we need all of the above for it to be usable.

**Comment by alanrenouf** [comment]
Unfortunately I am unable legally to give timelines unless you are under NDA, I wish i could tell you publicly but I quite like my job.

**Comment by PerMalmberg** [comment]
Fair enough.

At least we now know the APIs are coming, if not when. If needed, I'll reach out to you for further discussion at a later time.
