### ISSUE TITLE
HostSubSpecificationUpdateEvent and HostSpecificationRequireEvent definitions are missing

### ISSUE THREAD

**Issue by MaxxVolk** [vmware/vsphere-automation-sdk-.net#19]
Compiled Vim25Services.dll doesn't contain definitions for HostSubSpecificationUpdateEvent and HostSpecificationRequireEvent event types, which causes deserialization error while running all-possible-event-types capture.

## Environment
- SDK version: 
Unsure, but the latest vim-types.xsd donesn't have these definitions anyway.

- .NET version:
4.7.2

- vSphere version:
6.7.2

## Steps or code snippet to reproduce
Run event collector to capture all events.

## Actual behavior
Time-to-time, PropertyChange object contains raw xml elements (of type XmlAttribute or XmlElement) in val property of changeSet property instead of an ansessors of Event (like UserLoginSessionEvent for instance).

## Expected behavior
All returned events inherided from Vim25Api.Event.

**Comment by kunal-pmj** [comment]
Hi @MaxxVolk 

Current SDK supports following vCenter [releases](https://github.com/vmware/vsphere-automation-sdk-.net#supported-onprem-vcenter-releases) and 6.7U2 is not one of them. 

Thanks
Kunal

**Comment by MaxxVolk** [comment]
Hi @kunal-pmj, thank you for your confirmation. I also found this thread https://github.com/vmware/pyvmomi/issues/746, so it's confirmed to be fixed in the next release. Thank you for your hard work.
