### ISSUE TITLE
How to do guest shutdown?

### ISSUE THREAD

**Issue by basildane** [vmware/vsphere-automation-sdk-.net#2]
API looks great and I have it working for Power-ON and Power-OFF, but I need to do a graceful shutdown of guest OS's.  I've read the documentation but I cannot find the function.

**Comment by vinpai** [comment]
Currently, the guest shutdown API is not included within the new SDK, but it is high in our priority list. Until then you can use the soap based management sdk APIs for this task.

**Comment by basildane** [comment]
Thanks!
