### ISSUE TITLE
publish to nuget

### ISSUE THREAD

**Issue by mtrobbin** [vmware/vsphere-automation-sdk-.net#5]
I couldn't find where this sdk is available on nuget.  Can it be published via nuget package?  This would make dependency management significantly easier.

**Comment by vinpai** [comment]
Agree with you. We plan to do that soon, but currently its not available via nuget.

**Comment by EpicPhil** [comment]
Has there been any progress on this? I don't see the package on nuget.org.

**Comment by nssben** [comment]
@mtrobbin anyway your team could get this on nuget? I'm not seeing it there
